# Generated by Django 5.2.12 on 2026-07-13 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_supplierpayment_linked_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.category'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='inventory_supplierpayment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierrestockbill',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='inventory_restockbill_total_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='supplierrestockbill',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='inventory_restockbill_discount_amount_non_negative'),
        ),
    ]
