# Generated by Django 5.2.12 on 2026-07-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptionrecord',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='average_stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ideal stock level for calculation', max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, help_text='Cached popularity score (frequency of use)'),
        ),
        migrations.AlterField(
            model_name='supplierrestockitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
