# Generated by Django 5.2.12 on 2026-07-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_consumptionrecord_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcatalogitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Deactivated catalog entries stay listed (greyed) but are excluded from restock bills'),
        ),
    ]
