# Generated by Django 5.2.12 on 2026-07-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_shopcatalogitem_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='avg_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weighted-average purchase cost per unit, derived from restock bills', max_digits=10),
        ),
    ]
