# Generated by Django 5.2.12 on 2026-09-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_item_avg_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='markup_percent',
            field=models.PositiveSmallIntegerField(db_default=40, default=40, help_text='Markup on cost suggested for the customer unit price on a job card (whole %, 0–999)'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('markup_percent__lte', 999)), name='inventory_item_markup_percent_max'),
        ),
    ]
