# Generated by Django 5.2.12 on 2026-09-19 17:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_item_markup_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='suppliershop',
            name='opening_balance',
            field=models.DecimalField(db_default=Decimal('0'), decimal_places=2, default=Decimal('0'), help_text='Owed to this shop on go-live day, from before the system', max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='suppliershop',
            constraint=models.CheckConstraint(condition=models.Q(('opening_balance__gte', 0)), name='inventory_suppliershop_opening_balance_non_negative'),
        ),
        migrations.AddField(
            model_name='openingstock',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opening_stock', to='inventory.item'),
        ),
        migrations.AddConstraint(
            model_name='openingstock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_openingstock_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='openingstock',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gt', 0)), name='inventory_openingstock_unit_cost_positive'),
        ),
    ]
