# Generated by Django 5.2.12 on 2026-09-29 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_supplierpayment_recorded_by'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supplierrestockbill',
            name='inventory_restockbill_discount_amount_non_negative',
        ),
        migrations.RemoveField(
            model_name='supplierrestockbill',
            name='discount_amount',
        ),
    ]
