# Generated by Django 5.2.12 on 2026-06-02 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0033_bulkpaymenthistory_is_trashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpareShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('is_trashed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='jobcardspareitem',
            name='shop_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid to this shop for this specific item', max_digits=10),
        ),
        migrations.AlterField(
            model_name='jobcardspareitem',
            name='shop_name',
            field=models.CharField(blank=True, help_text='Shop where part was ordered (text copy for display)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobcardspareitem',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Linked SpareShop profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_items', to='workshop.spareshop'),
        ),
        migrations.CreateModel(
            name='SpareShopPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('TRANSFER', 'Bank Transfer')], default='CASH', max_length=20)),
                ('items_affected', models.PositiveIntegerField(default=0)),
                ('details', models.TextField(blank=True, help_text='JSON snapshot of which items received how much')),
                ('is_trashed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='workshop.spareshop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
