# Generated by Django 5.2.12 on 2026-06-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0034_spareshop_spareshoppayment_shop_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='spareshoppayment',
            name='note',
            field=models.CharField(blank=True, help_text='Optional description or reference', max_length=255, null=True),
        ),
    ]
