# Generated by Django 5.2.12 on 2026-06-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0035_spareshoppayment_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcardspareitem',
            name='ordered_date',
            field=models.DateField(blank=True, db_index=True, help_text='Auto-filled when status → ORDERED', null=True),
        ),
        migrations.AlterField(
            model_name='jobcardspareitem',
            name='received_date',
            field=models.DateField(blank=True, db_index=True, help_text='Auto-filled when status → RECEIVED', null=True),
        ),
    ]
