# Generated by Django 5.2.12 on 2026-06-14 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0037_remove_jobcardspareitem_shop_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcardspareitem',
            name='job_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spares', to='workshop.jobcard'),
        ),
    ]
