# Generated by Django 5.2.12 on 2026-06-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0038_alter_jobcardspareitem_job_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardspareitem',
            name='original_vehicle_info',
            field=models.CharField(blank=True, help_text='Stores car details if unassigned from a job card', max_length=255, null=True),
        ),
    ]
