# Generated by Django 5.2.12 on 2026-06-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0039_jobcardspareitem_original_vehicle_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concernsolution',
            name='concern',
            field=models.TextField(db_index=True, help_text='e.g., Sound when applying brake'),
        ),
    ]
