# Generated by Django 5.2.12 on 2026-06-19 13:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0040_add_concern_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('INCOME', 'Income (Cash In)'), ('EXPENSE', 'Expense (Cash Out)')], max_length=10)),
                ('category', models.CharField(choices=[('Electricity Bill', 'Electricity Bill'), ('Rent', 'Rent'), ('Courier Charges', 'Courier Charges'), ('Party Food', 'Party Food'), ('Water', 'Water'), ('Black Oil Sell', 'Black Oil Sell'), ('Scrap Sell', 'Scrap Sell'), ('Other Expense', 'Other Expense'), ('Other Income', 'Other Income')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Specific details (e.g., which courier, what food)', null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
