# Generated by Django 5.2.12 on 2026-06-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0041_cashbookentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbookentry',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cashbookentry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
