# Generated by Django 5.2.12 on 2026-06-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0042_alter_cashbookentry_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookentry',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('TRANSFER', 'Bank Transfer')], default='CASH', max_length=20),
        ),
    ]
