# Generated by Django 5.2.12 on 2026-06-19 15:29

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0043_cashbookentry_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbookentry',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='cashbookentry',
            index=models.Index(fields=['-date', '-created_at'], name='workshop_ca_date_9b2210_idx'),
        ),
        migrations.AddIndex(
            model_name='cashbookentry',
            index=models.Index(fields=['entry_type', '-date'], name='workshop_ca_entry_t_003aa6_idx'),
        ),
    ]
