# Generated by Django 5.2.12 on 2026-07-03 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0044_alter_cashbookentry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkpayer',
            name='job_cards',
        ),
        migrations.AddField(
            model_name='bulkpayer',
            name='total_billed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulkpayer',
            name='total_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='bulk_payer',
            field=models.ForeignKey(blank=True, help_text='Assigned bulk payer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to='workshop.bulkpayer'),
        ),
    ]
