# Generated by Django 5.2.12 on 2026-07-13 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0045_remove_bulkpayer_job_cards_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cashbookentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='workshop_cashbookentry_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='spareshoppayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='workshop_spareshoppayment_amount_positive'),
        ),
    ]
