# Generated by Django 5.2.12 on 2026-07-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0046_cashbookentry_workshop_cashbookentry_amount_positive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkpayer',
            name='advance_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Running credit from overpayments. Applied automatically on the next payment.', max_digits=12),
        ),
    ]
