# Generated by Django 5.2.12 on 2026-07-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0048_rename_delivered_to_completed'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jobcard',
            name='workshop_jo_is_dele_95b87f_idx',
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='completed',
            field=models.BooleanField(db_index=True, default=False, help_text='Job is Completed (marked via Completed button)'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='completed_date',
            field=models.DateField(blank=True, db_index=True, help_text='Auto-filled when job is marked as Completed', null=True),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['is_deleted', 'completed', '-updated_at'], name='workshop_jo_is_dele_2ded07_idx'),
        ),
    ]
