# Generated by Django 5.2.12 on 2026-07-24 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0049_remove_jobcard_workshop_jo_is_dele_95b87f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('JOBCARD', 'Job Card'), ('BULK_PAYMENT', 'Fleet Account Payment'), ('SHOP_PAYMENT', 'Spare-Shop Payment'), ('SUPPLIER_PAYMENT', 'Supplier Payment'), ('RESTOCK_BILL', 'Restock Bill'), ('CASHBOOK', 'Cashbook Entry')], db_index=True, max_length=20)),
                ('entity_label', models.CharField(help_text='Human-readable identity of the deleted record', max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Financial magnitude, if any', max_digits=12, null=True)),
                ('snapshot', models.JSONField(default=dict, help_text='Full readable copy of the deleted record for later reference')),
                ('reason', models.CharField(blank=True, help_text='Optional note entered at delete time', max_length=255)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deletion Log',
                'verbose_name_plural': 'Deletion History',
                'ordering': ['-deleted_at'],
                'indexes': [models.Index(fields=['entity_type', '-deleted_at'], name='workshop_de_entity__e300eb_idx')],
            },
        ),
    ]
