# Generated by Django 5.2.12 on 2026-07-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0051_alter_deletionlog_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='role',
            field=models.CharField(choices=[('MECHANIC', 'Mechanic'), ('ASSISTANT_MECHANIC', 'Assistant Mechanic'), ('OFFICE_STAFF', 'Office Staff'), ('GENERAL_HELPER', 'General Helper')], default='MECHANIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Disable if this staff member leaves the workshop'),
        ),
    ]
