# Generated by Django 5.2.12 on 2026-07-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0052_mechanic_add_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='paid_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text="Set only when payment_status becomes PAID/BULK_PAID — Paid Bills filters on this, not updated_at, so an unrelated later edit never resurfaces an old bill under 'Today'", null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending (Unpaid)'), ('PAID', 'Fully Paid'), ('PARTIAL', 'Partially Paid'), ('BULK_PAID', 'Fleet Paid')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
