# Generated by Django 5.2.12 on 2026-07-26 15:58

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0053_jobcard_add_paid_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='current_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current monthly salary used by Salary & Advance settlement. Changing this only affects months settled after the change — already-saved months keep the salary that was in effect then.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='deletionlog',
            name='entity_type',
            field=models.CharField(choices=[('JOBCARD', 'Job Card'), ('BULK_PAYMENT', 'Fleet Account Payment'), ('SHOP_PAYMENT', 'Spare-Shop Payment'), ('SUPPLIER_PAYMENT', 'Supplier Payment'), ('RESTOCK_BILL', 'Restock Bill'), ('CASHBOOK', 'Cashbook Entry'), ('INVENTORY_ITEM', 'Inventory Product'), ('SALARY_ADVANCE', 'Salary Advance'), ('SALARY_PAYMENT', 'Salary Payment')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advances', to='workshop.mechanic')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True, help_text='Always the 1st of the month it represents', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPaymentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leave_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5)),
                ('advance_used', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='workshop.salarypayment')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payment_lines', to='workshop.mechanic')),
            ],
            options={
                'ordering': ['staff__name'],
                'unique_together': {('payment', 'staff')},
            },
        ),
    ]
