# Generated by Django 5.2.12 on 2026-07-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0054_mechanic_current_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='Optional alternative login identifier. Leave empty for Office/Floor accounts.', max_length=20, null=True, unique=True),
        ),
    ]
