# Generated by Django 5.2.12 on 2026-07-29 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_item_avg_cost'),
        ('workshop', '0059_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardspareitem',
            name='customer_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Customer price per unit (optional; drives total_price when set)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobcardspareitem',
            name='item',
            field=models.ForeignKey(blank=True, help_text='The stock product drawn (INVENTORY rows only). PROTECT: a product used on a job card must not be deletable out from under that history.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_card_uses', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='jobcardspareitem',
            name='source',
            field=models.CharField(choices=[('SHOP', 'Spare Shop'), ('INVENTORY', 'Inventory')], db_index=True, default='SHOP', help_text='Which route this part reached the car by — never inferred, always stored', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobcardspareitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Customer price — the figure that bills, shown in the UI as 'Customer Price'", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobcardspareitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit (shop price, or warehouse average cost)', max_digits=10, null=True),
        ),
    ]
