# Generated by Django 5.2.12 on 2026-08-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0061_alter_deletionlog_entity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletionlog',
            name='entity_type',
            field=models.CharField(choices=[('JOBCARD', 'Job Card'), ('BULK_PAYMENT', 'Fleet Account Payment'), ('SHOP_PAYMENT', 'Spare-Shop Payment'), ('SUPPLIER_PAYMENT', 'Supplier Payment'), ('RESTOCK_BILL', 'Restock Bill'), ('CASHBOOK', 'Cashbook Entry'), ('INVENTORY_ITEM', 'Inventory Product'), ('SALARY_ADVANCE', 'Salary Advance'), ('SALARY_PAYMENT', 'Salary Payment'), ('UNASSIGNED_SPARE', 'Unassigned Spare'), ('MASTER_DATA', 'Master List Entry')], db_index=True, max_length=20),
        ),
    ]
