# Generated by Django 5.2.12 on 2026-08-03 03:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0062_alter_deletionlog_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypaymentline',
            name='overtime_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Overtime earned this month, as a single amount. Added to the net, so the wage cost the Profit page reads (net + advance) includes it without any further arithmetic.', max_digits=10),
        ),
    ]
