# Generated by Django 5.2.12 on 2026-08-03 07:47

from django.db import migrations, models


def close_all_but_the_newest(apps, schema_editor):
    """
    Every month already settled except the most recent one is closed.

    Without this backfill the flag starts False everywhere, so on the first
    deploy the entire settled history would be editable again until each month
    happened to be superseded a second time — which for finished months never
    happens.
    """
    SalaryPayment = apps.get_model('workshop', 'SalaryPayment')
    newest = SalaryPayment.objects.order_by('-month').first()
    qs = SalaryPayment.objects.all()
    if newest:
        qs = qs.exclude(pk=newest.pk)
    qs.update(superseded=True)


def reopen_all(apps, schema_editor):
    """Reverse: clear the flag. The column is dropped straight afterwards."""
    apps.get_model('workshop', 'SalaryPayment').objects.update(superseded=False)


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0063_salarypaymentline_overtime_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='superseded',
            field=models.BooleanField(db_index=True, default=False, help_text='Set once a LATER month has been settled. Never unset — a closed month stays closed even if that later settlement is deleted, so nobody can walk backwards through history one delete at a time.'),
        ),
        migrations.RunPython(close_all_but_the_newest, reopen_all),
    ]
