# Generated by Django 5.2.12 on 2026-08-03 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0064_salarypayment_superseded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cashbookentry',
            index=models.Index(fields=['category'], name='workshop_ca_categor_dff6bc_idx'),
        ),
    ]
