# Generated by Django 5.2.12 on 2026-08-05 02:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0066_jobcard_labour_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_number', models.CharField(blank=True, help_text='Auto-generated (e.g. EST-26-001)', max_length=20, null=True, unique=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('customer_name', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('customer_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('mileage', models.CharField(blank=True, max_length=20, null=True)),
                ('labour_amount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total quoted labour for every job line (entered once, not per line)', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, help_text='Internal note — never printed', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estimate',
                'verbose_name_plural': 'Estimates',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EstimateJobLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_lines', to='workshop.estimate')),
            ],
        ),
        migrations.CreateModel(
            name='EstimatePartLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('customer_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Quoted price per unit (optional; drives amount when set)', max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Quoted price for this line — the figure that prints', max_digits=10, null=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='workshop.estimate')),
            ],
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['-date', '-id'], name='workshop_es_date_bd18a6_idx'),
        ),
    ]
