# Generated by Django 5.2.12 on 2026-08-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0067_estimate_estimatejobline_estimatepartline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='car_color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Silver', 'Silver'), ('Grey', 'Grey'), ('Red', 'Red'), ('Light Blue', 'Light Blue'), ('Blue', 'Blue'), ('Dark Blue', 'Dark Blue'), ('Yellow', 'Yellow'), ('Light Green', 'Light Green'), ('Green', 'Green'), ('Dark Green', 'Dark Green'), ('Brown', 'Brown'), ('Dark Brown', 'Dark Brown'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='car_color_other',
            field=models.CharField(blank=True, help_text="Specific colour name if 'Other' is selected", max_length=100, null=True),
        ),
    ]
