# Generated by Django 5.2.12 on 2026-08-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0068_estimate_car_color_estimate_car_color_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='notes',
            field=models.CharField(blank=True, help_text="Internal note — never printed on the customer's bill", max_length=255),
        ),
    ]
