# Generated by Django 5.2.12 on 2026-08-18 19:02
#
# Job card photos: `JobCardPhoto` (one table for car and spare photos, told
# apart by which FK is set, with a CheckConstraint making "exactly one subject"
# a database rule rather than an advisory one) and `OrphanedPhotoBlob` (storage
# keys awaiting collection by `sweep_photo_blobs`). Purely ADDITIVE — nothing
# existing gains a column, so no job card, bill, ledger or report changes value.
#
# The `unit_price` AlterField is a tag-along: a help_text correction left over
# from the 2026-08-17 "a shop line costs what was typed" change that was never
# captured in a migration. help_text touches no database column, so it is a
# no-op at the schema level — it is here only so `makemigrations` stops
# re-proposing it.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0069_jobcard_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrphanedPhotoBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterField(
            model_name='jobcardspareitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Workshop cost: the shop's line total (SHOP), or the warehouse average cost per unit (INVENTORY)", max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='JobCardPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taken_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('job_card', models.ForeignKey(blank=True, help_text='Set for a CAR photo. Null for a spare photo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='workshop.jobcard')),
                ('spare', models.ForeignKey(blank=True, help_text='Set for a SPARE photo. Null for a car photo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='workshop.jobcardspareitem')),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos_taken', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-taken_at'],
                'indexes': [models.Index(fields=['job_card', '-taken_at'], name='workshop_jo_job_car_eb8178_idx'), models.Index(fields=['spare', '-taken_at'], name='workshop_jo_spare_i_73d4e6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('job_card__isnull', False), ('spare__isnull', True)), models.Q(('job_card__isnull', True), ('spare__isnull', False)), _connector='OR'), name='photo_belongs_to_exactly_one_subject')],
            },
        ),
    ]
