# Generated by Django 5.2.12 on 2026-08-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0072_alter_bulkpaymenthistory_options_and_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkpaymenthistory',
            name='note',
            field=models.CharField(blank=True, help_text='Optional description or reference', max_length=255, null=True),
        ),
    ]
