# Generated by Django 5.2.12 on 2026-08-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0073_bulkpaymenthistory_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='detail',
            field=models.CharField(blank=True, help_text='Supporting context, printed under the headline beside the category', max_length=255),
        ),
    ]
