# Generated by Django 5.2.12 on 2026-08-30 17:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0074_notification_detail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletionlog',
            name='entity_type',
            field=models.CharField(choices=[('JOBCARD', 'Job Card'), ('BULK_PAYMENT', 'Fleet Account Payment'), ('SHOP_PAYMENT', 'Spare-Shop Payment'), ('SUPPLIER_PAYMENT', 'Supplier Payment'), ('RESTOCK_BILL', 'Restock Bill'), ('CASHBOOK', 'Cashbook Entry'), ('INVENTORY_ITEM', 'Inventory Product'), ('SALARY_ADVANCE', 'Salary Advance'), ('SALARY_PAYMENT', 'Salary Payment'), ('UNASSIGNED_SPARE', 'Unassigned Spare'), ('OWNER_WITHDRAWAL', 'Owner Withdrawal'), ('MASTER_DATA', 'Master List Entry')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='OwnerWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('TRANSFER', 'Bank Transfer')], default='CASH', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(help_text='Which owner took the money', on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['-date', '-created_at'], name='workshop_ow_date_8dfe75_idx'), models.Index(fields=['owner', '-date'], name='workshop_ow_owner_i_1df00a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='workshop_ownerwithdrawal_amount_positive')],
            },
        ),
    ]
