# Generated by Django 5.2.12 on 2026-09-03 17:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0075_alter_deletionlog_entity_type_ownerwithdrawal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletionlog',
            name='entity_type',
            field=models.CharField(choices=[('JOBCARD', 'Job Card'), ('BULK_PAYMENT', 'Fleet Account Payment'), ('SHOP_PAYMENT', 'Spare-Shop Payment'), ('SUPPLIER_PAYMENT', 'Supplier Payment'), ('RESTOCK_BILL', 'Restock Bill'), ('CASHBOOK', 'Cashbook Entry'), ('INVENTORY_ITEM', 'Inventory Product'), ('SALARY_ADVANCE', 'Salary Advance'), ('SALARY_PAYMENT', 'Salary Payment'), ('UNASSIGNED_SPARE', 'Unassigned Spare'), ('OWNER_WITHDRAWAL', 'Owner Withdrawal'), ('RENT_DEPOSIT', 'Rent Deposit'), ('MASTER_DATA', 'Master List Entry')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='RentDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_deposits_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['-date', '-created_at'], name='workshop_re_date_63bec4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='workshop_rentdeposit_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='RentRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(help_text='The first month this rent applies to', unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_rates_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='workshop_rentrate_amount_positive')],
            },
        ),
    ]
