# Generated by Django 5.2.12 on 2026-09-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0077_alter_deletionlog_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='chassis_code',
            field=models.CharField(blank=True, help_text='Platform code, e.g. F30 or W205', max_length=20, null=True, verbose_name='Chassis Code'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='vin',
            field=models.CharField(blank=True, help_text="17-character Vehicle Identification Number (the RC book's Chassis No.)", max_length=17, null=True, verbose_name='VIN'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='chassis_code',
            field=models.CharField(blank=True, help_text='Platform code, e.g. F30 or W205', max_length=20, null=True, verbose_name='Chassis Code'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='vin',
            field=models.CharField(blank=True, help_text="17-character Vehicle Identification Number (the RC book's Chassis No.)", max_length=17, null=True, verbose_name='VIN'),
        ),
    ]
