# Generated by Django 5.2.12 on 2026-09-17 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0078_jobcard_estimate_chassis_code_vin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OldBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(help_text='As printed on the paper bill, e.g. JB-26-097', max_length=20, unique=True)),
                ('bill_date', models.DateField(db_index=True, help_text='The DATE printed on the bill')),
                ('registration_number', models.CharField(db_index=True, max_length=50)),
                ('brand_name', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('mileage', models.CharField(blank=True, max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('labour_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Old Bill',
                'verbose_name_plural': 'Old Bills',
            },
        ),
        migrations.CreateModel(
            name='OldBillJobLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('old_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_lines', to='workshop.oldbill')),
            ],
        ),
        migrations.CreateModel(
            name='OldBillPartLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('old_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_lines', to='workshop.oldbill')),
            ],
        ),
        migrations.AddConstraint(
            model_name='oldbill',
            constraint=models.CheckConstraint(condition=models.Q(('labour_amount__gte', 0)), name='workshop_oldbill_labour_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='oldbill',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='workshop_oldbill_total_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='oldbillpartline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__isnull', True), ('quantity__gt', 0), _connector='OR'), name='workshop_oldbillpartline_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='oldbillpartline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gte', 0), _connector='OR'), name='workshop_oldbillpartline_amount_not_negative'),
        ),
    ]
