# Generated by Django 5.2.12 on 2026-09-19 17:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0079_old_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='spareshop',
            name='opening_balance',
            field=models.DecimalField(db_default=Decimal('0'), decimal_places=2, default=Decimal('0'), help_text='Owed to this shop on go-live day, from before the system', max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='spareshop',
            constraint=models.CheckConstraint(condition=models.Q(('opening_balance__gte', 0)), name='workshop_spareshop_opening_balance_non_negative'),
        ),
    ]
