# Generated by Django 5.2.12 on 2026-09-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0081_legacy_data_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('TRANSFER', 'Bank Transfer')], max_length=20, null=True),
        ),
    ]
