# Generated by Django 5.2.12 on 2026-09-23 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0082_job_card_payment_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('JOBCARD', 'Job Card'), ('RESTOCK_BILL', 'Restock Bill'), ('CASHBOOK', 'Cashbook Entry')], db_index=True, max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text="The edited record's id — no FK, so the history outlives it", null=True)),
                ('entity_label', models.CharField(help_text='Human-readable identity of the edited record, frozen at the time', max_length=255)),
                ('changes', models.JSONField(default=list, help_text='What moved: [{field, kind, before, after}], money only')),
                ('edited_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Edit Log',
                'verbose_name_plural': 'Edit History',
                'ordering': ['-edited_at'],
                'indexes': [models.Index(fields=['entity_type', '-edited_at'], name='workshop_ed_entity__bd0d08_idx')],
            },
        ),
    ]
