# Generated by Django 5.2.12 on 2026-09-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0084_payment_recorded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editlog',
            name='entity_type',
            field=models.CharField(choices=[('JOBCARD', 'Job Card'), ('RESTOCK_BILL', 'Restock Bill'), ('CASHBOOK', 'Cashbook Entry'), ('RENT_DEPOSIT', 'Rent Deposit')], db_index=True, max_length=20),
        ),
    ]
