# Generated by Django 5.2.12 on 2026-09-29 18:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0085_editlog_rent_deposit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spareshop',
            name='total_discount_amount',
            field=models.DecimalField(db_default=Decimal('0'), decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='deletionlog',
            name='entity_type',
            field=models.CharField(choices=[('JOBCARD', 'Job Card'), ('BULK_PAYMENT', 'Fleet Account Payment'), ('SHOP_PAYMENT', 'Spare-Shop Payment'), ('SUPPLIER_PAYMENT', 'Supplier Payment'), ('RESTOCK_BILL', 'Restock Bill'), ('CASHBOOK', 'Cashbook Entry'), ('INVENTORY_ITEM', 'Inventory Product'), ('SALARY_ADVANCE', 'Salary Advance'), ('SALARY_PAYMENT', 'Salary Payment'), ('UNASSIGNED_SPARE', 'Unassigned Spare'), ('OWNER_WITHDRAWAL', 'Owner Withdrawal'), ('RENT_DEPOSIT', 'Rent Deposit'), ('RENT_RATE', 'Rent Rate'), ('SHOP_DISCOUNT', 'Spare-Shop Discount'), ('SUPPLIER_DISCOUNT', 'Supplier Discount'), ('MASTER_DATA', 'Master List Entry')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='SpareShopDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='The day the shop let us off.')),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_shop_discounts_recorded', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='workshop.spareshop')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='workshop_spareshopdiscount_amount_positive')],
            },
        ),
    ]
